name: workflow1
on:
  push:
  create:
  release:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: dump
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
      shell: bash